/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadGP13.vistas;

import javax.swing.JOptionPane;
import universidadGP13.accesoAdatos.MateriaData;
import universidadGP13.entidades.Materia;

/**
 *
 * @author Hernan
 */
public class FormularioMateria extends javax.swing.JInternalFrame {

    private MateriaData md = new MateriaData();

    /**
     * Creates new form vistasMateria
     */
    public FormularioMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMateria = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlAnio = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jtfCodigoMat = new javax.swing.JTextField();
        jtfNombreMat = new javax.swing.JTextField();
        jtfAnioMat = new javax.swing.JTextField();
        jrbEstadoMat = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();

        jlMateria.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jlMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMateria.setText("Materia");
        jlMateria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlCodigo.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCodigo.setText("Código:");

        jlNombre.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNombre.setText("Nombre:");

        jlAnio.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlAnio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlAnio.setText("Año:");

        jlEstado.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlEstado.setText("Estado:");

        jbNuevo.setText("Nuevo");
        jbNuevo.setPreferredSize(new java.awt.Dimension(80, 30));
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.setPreferredSize(new java.awt.Dimension(80, 30));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.setPreferredSize(new java.awt.Dimension(80, 30));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setEnabled(false);
        jbEliminar.setPreferredSize(new java.awt.Dimension(80, 30));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jtfNombreMat.setEnabled(false);

        jtfAnioMat.setEnabled(false);

        jrbEstadoMat.setEnabled(false);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCodigoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jrbEstadoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfAnioMat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCodigoMat, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNombreMat)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfAnioMat, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbEstadoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        jrbEstadoMat.setEnabled(false);
        boolean flag = validarCodigo();
        try{
        if (flag) {
            activarCampos();
            jbEliminar.setEnabled(true);
            Materia materia = md.buscarMateria(Integer.parseInt(jtfCodigoMat.getText()));
            jtfNombreMat.setText(materia.getNombre());
            jtfAnioMat.setText(materia.getAnioMateria() + "");
            jrbEstadoMat.setSelected(materia.isEstado());
        }
        } catch (NullPointerException e){
            limpiarCampos();
            desactivarCampos();
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiarCampos();
        activarCampos();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        boolean flag = validarCampos();
        try{
        if (flag && jtfCodigoMat.getText().isEmpty()) {
            Materia materia = new Materia(jtfNombreMat.getText(), Integer.parseInt(jtfAnioMat.getText()), jrbEstadoMat.isSelected());
            md.guardarMateria(materia);
            limpiarCampos();
            desactivarCampos();
        } else {
            Materia materia = new Materia(Integer.parseInt(jtfCodigoMat.getText()), jtfNombreMat.getText(), Integer.parseInt(jtfAnioMat.getText()), jrbEstadoMat.isSelected());
            md.modificarMateria(materia);
            limpiarCampos();
            desactivarCampos();
        }
        } catch (NumberFormatException e){
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        md.eliminarMateria(Integer.parseInt(jtfCodigoMat.getText()));
        limpiarCampos();
        desactivarCampos();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private boolean validarCodigo() {
        if (!jtfCodigoMat.getText().equals("")) {
            String val1 = "[0-9]*";
            if (!jtfCodigoMat.getText().matches(val1)) {
                JOptionPane.showMessageDialog(this, "En el apartado código solo pueden ser ingresados números.");
                jtfCodigoMat.requestFocus();
                return false;
            }
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "¡El apartado código no debe estar vacío!");
            return false;
        }
    }

    private boolean validarCampos() {
        if (!jtfNombreMat.getText().equals("") && !jtfAnioMat.getText().equals("")) {
            String val2 = "[0-9a-zA-ZáéíóúÁÉÍÓÚ\\s]*";
            if (!jtfNombreMat.getText().matches(val2)) {
                JOptionPane.showMessageDialog(this, "En el apartado nombre solo pueden ser ingresadas letras.");
                jtfNombreMat.requestFocus();
                return false;
            }
            String val3 = "[0-9]*";
            int cmateria = 0;
            if (jtfAnioMat.getText().matches(val3) && !jtfAnioMat.getText().isEmpty()) {
                cmateria = Integer.parseInt(jtfAnioMat.getText());
            }
            if (!jtfAnioMat.getText().matches(val3)) {
                JOptionPane.showMessageDialog(this, "En el apartado año solo pueden ser ingresados números.");
                jtfAnioMat.requestFocus();
                return false;
            } else if (!jtfAnioMat.getText().isEmpty() && (cmateria < 1 || cmateria > 5)) {
                JOptionPane.showMessageDialog(this, "El número ingresado en el apartado año debe ser entre 1 y 5.");
                jtfAnioMat.requestFocus();
                return false;
            }
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "¡Los apartados nombre y año no deben estar vacíos!");
            return false;
        }
    }

    private void activarCampos() {
        jtfCodigoMat.setEditable(false);
        jtfNombreMat.setEnabled(true);
        jtfAnioMat.setEnabled(true);
        jrbEstadoMat.setEnabled(true);
        jbGuardar.setEnabled(true);
    }

    private void limpiarCampos() {
        jtfCodigoMat.setEditable(false);
        jtfCodigoMat.setText("");
        jtfNombreMat.setText("");
        jtfAnioMat.setText("");
        jrbEstadoMat.setSelected(false);
    }

    private void desactivarCampos() {
        jtfCodigoMat.setEditable(true);
        jtfNombreMat.setEnabled(false);
        jtfAnioMat.setEnabled(false);
        jrbEstadoMat.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbEliminar.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlAnio;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlMateria;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JRadioButton jrbEstadoMat;
    private javax.swing.JTextField jtfAnioMat;
    private javax.swing.JTextField jtfCodigoMat;
    private javax.swing.JTextField jtfNombreMat;
    // End of variables declaration//GEN-END:variables
}
