/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadGP13.vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import universidadGP13.accesoAdatos.AlumnoData;
import universidadGP13.accesoAdatos.MateriaData;

/**
 *
 * @author valer
 */
public class menu extends javax.swing.JFrame {

    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon (getClass().getResource("/Imagenes/ULP.jpg"));
        Image miImagen = icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jmiFormularioAlumno = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jmiFormularioMateria = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jmFormularioInscripcion = new javax.swing.JMenuItem();
        jmiFormularioNotas = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jmiAxM = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumno");

        jmiFormularioAlumno.setText("Formulario de Alumno");
        jmiFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jmiFormularioAlumno);

        jMenuBar1.add(jMenuAlumno);

        jMenuMateria.setText("Materia");

        jmiFormularioMateria.setText("Formulario de Materias");
        jmiFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriaActionPerformed(evt);
            }
        });
        jMenuMateria.add(jmiFormularioMateria);

        jMenuBar1.add(jMenuMateria);

        jMenuAdmin.setText("Administracion");

        jmFormularioInscripcion.setText("Manejo de Inscripciones");
        jmFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioInscripcionActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jmFormularioInscripcion);

        jmiFormularioNotas.setText("Manipulacion de Notas");
        jmiFormularioNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioNotasActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jmiFormularioNotas);

        jMenuBar1.add(jMenuAdmin);

        jMenuConsulta.setText("Consultas");

        jmiAxM.setText("Alumnos por Materia");
        jmiAxM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAxMActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jmiAxM);

        jMenuBar1.add(jMenuConsulta);

        jmSalir.setText("Salir");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioAlumnoActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioAlumno vistaA = new FormularioAlumno();
        vistaA.setVisible(true);
        jDesktopPane1.add(vistaA);
        jDesktopPane1.moveToFront(vistaA);
    }//GEN-LAST:event_jmiFormularioAlumnoActionPerformed

    private void jmiFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioMateria vistaM = new FormularioMateria();
        vistaM.setVisible(true);
        jDesktopPane1.add(vistaM);
        jDesktopPane1.moveToFront(vistaM);
    }//GEN-LAST:event_jmiFormularioMateriaActionPerformed

    private void jmFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioInscripcionActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioInscripcion vistaI = new FormularioInscripcion();
        vistaI.setVisible(true);
        jDesktopPane1.add(vistaI);
        jDesktopPane1.moveToFront(vistaI);
    }//GEN-LAST:event_jmFormularioInscripcionActionPerformed

    private void jmiFormularioNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioNotasActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FormularioNotas vistaN = new FormularioNotas();
        vistaN.setVisible(true);
        jDesktopPane1.add(vistaN);
        jDesktopPane1.moveToFront(vistaN);
    }//GEN-LAST:event_jmiFormularioNotasActionPerformed

    private void jmiAxMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAxMActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        AlumnosPorMateria vistaAxM = new AlumnosPorMateria();
        vistaAxM.setVisible(true);
        jDesktopPane1.add(vistaAxM);
        jDesktopPane1.moveToFront(vistaAxM);
    }//GEN-LAST:event_jmiAxMActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenuItem jmFormularioInscripcion;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAxM;
    private javax.swing.JMenuItem jmiFormularioAlumno;
    private javax.swing.JMenuItem jmiFormularioMateria;
    private javax.swing.JMenuItem jmiFormularioNotas;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
